
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eva
 */
public class buildinfo extends javax.swing.JFrame {

    
      Connection con=null;
PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form buildinfo
     */
    public buildinfo() {
        initComponents();
        set();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        homepage = new javax.swing.JButton();
        adminMaster = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        locationlbl = new javax.swing.JLabel();
        floorroom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(102, 0, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Building Information");

        homepage.setBackground(new java.awt.Color(102, 0, 102));
        homepage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        homepage.setForeground(new java.awt.Color(204, 0, 0));
        homepage.setText("Home");
        homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepageActionPerformed(evt);
            }
        });

        adminMaster.setBackground(new java.awt.Color(102, 0, 102));
        adminMaster.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adminMaster.setForeground(new java.awt.Color(153, 0, 0));
        adminMaster.setText("Login");
        adminMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminMasterActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Hostel Name :");

        namelbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namelbl.setText("Shekh Hasina Hall");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Hostel Location :");

        locationlbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        locationlbl.setText("Karnakhati");

        floorroom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        floorroom.setForeground(new java.awt.Color(204, 0, 51));
        floorroom.setText("Floor Information");
        floorroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorroomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(homepage)
                .addGap(18, 18, 18)
                .addComponent(adminMaster)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(16, 16, 16)
                                .addComponent(locationlbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(namelbl))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(floorroom)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namelbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(locationlbl))
                .addGap(36, 36, 36)
                .addComponent(floorroom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homepage)
                    .addComponent(adminMaster))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepageActionPerformed
        // TODO add your handling code here:
        
          homepage homepage = new homepage();
         this.dispose();
        homepage.setVisible(true);
    }//GEN-LAST:event_homepageActionPerformed

    private void floorroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorroomActionPerformed
        
  floorroom floorroom = new floorroom();
         this.dispose();
        floorroom.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_floorroomActionPerformed

    private void adminMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminMasterActionPerformed
adminMaster adminMaster = new adminMaster();
        this.dispose();
        adminMaster.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_adminMasterActionPerformed

    
         private void set(){
            
             try{
         
          
           
          con=Connect.ConnectDB();
             
         
         String sql = "SELECT * FROM hall WHERE ID = '1' ";
         pst = con.prepareStatement(sql);
         
         rs=pst.executeQuery();
         
         //int selectedRowIndex = pst.getSelectedRow();
       if( rs.next()){
           
             String name = rs.getString("name");
             namelbl.setText(name);
             
              String location = rs.getString("location");
             locationlbl.setText(location );
             
             /*
              String floor = rs.getString("floor");
             floorlbl.setText(floor);
             
              String room = rs.getString("room");
             roomlbl.setText(room);
             
             String bed = rs.getString("bed");
             bedlbl.setText(bed);
             
             String tbl = rs.getString("tbl");
             tbllbl.setText(tbl);
             
             String fan = rs.getString("fan");
             fanlbl.setText(fan);
             
             String tube= rs.getString("tube");
             tubelbl.setText(tube);
             
              String trank= rs.getString("trank");
             tranklbl.setText(trank);
             
             */
             
             
       }
         
   
 }
     catch(Exception ex){
         JOptionPane.showMessageDialog(null, ex);
         
     }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buildinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buildinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buildinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buildinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buildinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminMaster;
    private javax.swing.JButton floorroom;
    private javax.swing.JButton homepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel locationlbl;
    private javax.swing.JLabel namelbl;
    // End of variables declaration//GEN-END:variables
}
